@startuml
abstract class Field {
    + <<virtual>> IsNotOccupied() : bool
    + IsVillage : bool <<get>> <<set>>
    + IsBottomRow : bool <<get>> <<set>>
    + <<virtual>> IsMoveAllowed() : bool
    + <<virtual>> Crowded() : bool
    + {abstract} <<override>> ToString() : string
}
class "List`1"<T> {
}
Field o-> "Pieces<Piece>" "List`1"
Field --> "TempPiece" Piece
Field --> "LeftConnectedField" Field
Field --> "RightConnectedField" Field
Field --> "TopConnectedField" Field
Field --> "DownConnectedField" Field
@enduml
