@startuml
class PlayerPiece {
    + <<override>> MoveAllowed(fieldTo:Field, die:Die) : bool
    + <<override>> NextPiece(die:Die) : Piece
    + PlayerPiece(name:string)
}
Piece <|-- PlayerPiece
PlayerPiece --> "StartField" StartField
PlayerPiece --> "PieceOwner" Player
@enduml
